version: '3.4'
services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      -  "27017:27017"
    volumes:
      -  mongo_data:/data/db 

  basketdb:
    container_name: basketdb
    restart: always    
    ports:
        - "6379:6379"
 

  discountdb:
    container_name: discountdb
    restart: always    
    environment:
      -  POSTGRES_USER=admin
      -  POSTGRES_PASSWORD=admin12345
      -  POSTGRES_DB=DiscountDb
    ports:
        - "5432:5432"
    volumes:
      -  postgres_data:/var/lib/postgresql/data/ 

  # pgadmin:
  #   container_name: pgadmin
  #   environment:
  #     -  PGADMIN_DEFAULT_EMAIL=Islamadmin@aspnetrun.com
  #     -  PGADMIN_DEFAULT_PASSWORD=admin12345
  #   restart: always
  #   ports:
  #     -  "5050:80"
  #   volumes:
  #     -  pgadmin_data:/root/.pgadmin  


  portainer:
    container_name: portainer
    restart: always    
    environment:
      -  ASPNETCORE_HTTPS_PORTS=8000
      -  ASPNETCORE_HTTPS_PORTS=9443
    ports:
        - "8080:8000"
        - "9443:9443"
    volumes:
      -  /var/run/docker.sock:/var/run/docker.sock
      -  portainer_data:/data 

  catalog.api:
    container_name: catalog.api
    environment:
      -  ASPNETCORE_ENVIRONMENT=DockerCompose
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      -  catalogdb
    ports:
      - "8000:8080"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      -  basketdb
    ports:
      - "8001:8080"


  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      -  discountdb
    ports:
      - "8002:8080"

